# Ultralytics YOLOv8 Dataset Configuration
# Path to dataset
path: ../datasets/football_v1  # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val      # val images (relative to 'path')
test:                # test images (optional)

# Classes
names:
  0: ball
  1: goalkeeper
  2: player
  3: referee

# Hyperparameters (Optional override)
# lr0: 0.01
# lrf: 0.01
