# Ultralytics YOLOv8-Pose Dataset Configuration
# Path to dataset
path: ../datasets/pitch_keypoints_v1
train: images/train
val: images/val

# Keypoints
kpt_shape: [27, 3] # [number of keypoints, dim (2 for x,y or 3 for x,y,visible)]

# 翻转映射 (不要动)
# 当图片左右翻转时，左边的点会变成右边的点。
# 映射逻辑:
# 中线点(0-4) -> 不变
# 左半场点(5-15) <-> 右半场点(16-26)
flip_idx: [
  0, 1, 2, 3, 4,
  16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
  5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
]

names:
  0: football-pitch