# 数据集路径 (相对于执行命令的目录，或者写绝对路径)
path: /Users/dreaner/Dev/Tactix/data/SoccerNet/yolo_ready
train: images/train
val: images/valid

# 关键点定义 (不要动)
kpt_shape: [27, 3]

# 翻转映射 (不要动)
# 当图片左右翻转时，左边的点会变成右边的点。
# 映射逻辑:
# 中线点(0-4) -> 不变
# 左半场点(5-15) <-> 右半场点(16-26)
flip_idx: [
  0, 1, 2, 3, 4,
  16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
  5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
]

names:
  0: football-pitch