system:
  device: "mps"  # æˆ– cuda

paths:
  player_model: "assets/weights/yolov8m.pt"
  pitch_model: "assets/weights/best.pt"
  input_video: "assets/videos/InterGoalClip.mp4"
  output_video: "assets/output/result_v2.mp4"
  pitch_image: "assets/pitch_template.png"

parameters:
  detector_conf: 0.3
  pitch_conf: 0.5
  pass_max_dist: 400